name: "Lint/Validate files"

on:
  pull_request:

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: yamllint -v
      - name: Validate YAML file
        run: find . \( -name "*.yml" -o -name "*.yaml" \) | xargs yamllint
